ALTER USER 'root'@'localhost' IDENTIFIED BY 'PASSWORD';
CREATE DATABASE customer_behavior;
USE customer_behavior;
SHOW TABLES;
SELECT * FROM customer_data LIMIT 10;
SELECT COUNT(*) FROM customer_data;

-- Q1. What is the total revenue generated by male vs female customers?

SELECT gender, SUM(purchase_amount) as revenue
FROM customer_data
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount 
FROM customer_data
WHERE discount_applied='YES' AND purchase_amount>=(SELECT AVG(purchase_amount) FROM customer_data);


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, AVG(review_rating) as avg_product_rating
FROM customer_data
GROUP BY item_purchased
ORDER BY avg_product_rating desc
LIMIT 5;


-- Q4. Compare the average purchase amounts between standard and express shipping?

SELECT shipping_type, ROUND(avg(purchase_amount),2) as avg_purchase_amount
FROM customer_data
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between
--  subscribers and non subscribers

SELECT subscription_status, 
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue 
FROM customer_data
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, 
ROUND(100*SUM(CASE WHEN discount_applied='YES' THEN 1 ELSE 0 END)/COUNT(*), 2) as discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5;

-- Q7. Segment customers into new, returing, and loyal based on their total number of previous purchases, and 
-- show the count of each segment?

with customer_type as (
SELECT customer_id, previous_purchases,
CASE
 WHEN previous_purchases=1 THEN 'New'
 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
 ELSE 'Loyal'
END as customer_segment
 FROM customer_data
)

SELECT customer_segment, COUNT(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

with item_counts as (
SELECT category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer_data
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank<=3;

-- Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status, COUNT(customer_id) as repeat_buyers
FROM customer_data
WHERE previous_purchases>5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each group?

SELECT age_group, SUM(purchase_amount) as total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue desc;
